In [ ]:
import pandas as pd
data = pd.read_csv("/content/output.csv")
dt = data.drop(data.columns[10:24], axis=1)  # drop Sun.- Sat. open/close times
# possibly also drop "full_address" etc. need to discuss

# New Section

In [54]:
# filter dataset: only keep restaurants
dt_restaurant = dt[dt['Is_Restaurants'] == 1]
# reverse the dummy variables (restaurant types) into one category 
rest_types = dt_restaurant[['business_id','Sandwiches', 'Fast Food',
       'Nightlife', 'Pizza', 'Bars', 'Mexican', 'Food',
       'American (Traditional)', 'Burgers', 'Chinese', 'Italian',
       'American (New)', 'Breakfast & Brunch', 'Thai', 'Indian', 'Sushi Bars',
       'Korean', 'Mediterranean', 'Japanese', 'Seafood', 'Middle Eastern',
       'Pakistani', 'Barbeque', 'Vietnamese', 'Asian Fusion', 'Diners',
       'Greek', 'Vegetarian']]
rest_types = rest_types.set_index('business_id')
rest_types["dummy_sum"] = rest_types.sum(axis=1)
dummy_type = rest_types[rest_types.dummy_sum == 1]
dummy_type = dummy_type.drop('dummy_sum',axis = 1)
dummy_type['type'] = dummy_type.idxmax(1)
business_type = dummy_type['type']

In [76]:
# new_dt is the restaurant dataset with restaurant type (dummy variables are dropped)
new_dt = pd.merge(dt_restaurant, business_type, left_on='business_id', right_index=True, how='left')
type_cols = ['Sandwiches', 'Fast Food',
       'Nightlife', 'Pizza', 'Bars', 'Mexican', 'Food',
       'American (Traditional)', 'Burgers', 'Chinese', 'Italian',
       'American (New)', 'Breakfast & Brunch', 'Thai', 'Indian', 'Sushi Bars',
       'Korean', 'Mediterranean', 'Japanese', 'Seafood', 'Middle Eastern',
       'Pakistani', 'Barbeque', 'Vietnamese', 'Asian Fusion', 'Diners',
       'Greek', 'Vegetarian']
new_dt = new_dt.drop(type_cols, axis =1)

In [78]:
new_dt

                  business_id  ...                  type_y
0      4bEjOyTaDG24SY5TxsaUNQ  ...      Breakfast & Brunch
1      zt1TpTuJ6y9n551sw9TaEg  ...                     NaN
2      2e2e7WgqU1BnpxmQL5jbfw  ...              Sandwiches
3      sIyHTizqAiGu12XMLX3N3g  ...                     NaN
4      aGbjLWzcrnEx2ZmMCFm3EA  ...                 Burgers
...                       ...  ...                     ...
65509  8P_GOw4u9EumQR1yZTxI8w  ...                   Pizza
65512  iuQi8l6qW_EKj-ZoqYeIKg  ...  American (Traditional)
65522  7hvtFt_oea5UncTQ1WBlyA  ...                 Chinese
65530  wbndBnssRoL2DM8sd8OaMA  ...                 Mexican
65533  k7zTofoKHGixABJiRb-phg  ...                 Chinese

[20042 rows x 48 columns]